/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as Gta6ActivitiesRouteImport } from './routes/gta-6-activities'
import { Route as Gta6CharactersRouteImport } from './routes/gta-6-characters'
import { Route as Gta6GameplayRouteImport } from './routes/gta-6-gameplay'
import { Route as Gta6LeonidaRouteImport } from './routes/gta-6-leonida'
import { Route as Gta6LocationsRouteImport } from './routes/gta-6-locations'
import { Route as Gta6MapRouteImport } from './routes/gta-6-map'
import { Route as Gta6NewsRouteImport } from './routes/gta-6-news'
import { Route as Gta6OnlineRouteImport } from './routes/gta-6-online'
import { Route as Gta6PcReleaseDateRouteImport } from './routes/gta-6-pc-release-date'
import { Route as Gta6PlatformsRouteImport } from './routes/gta-6-platforms'
import { Route as Gta6PriceRouteImport } from './routes/gta-6-price'
import { Route as Gta6ReleaseDateRouteImport } from './routes/gta-6-release-date'
import { Route as Gta6TrailersRouteImport } from './routes/gta-6-trailers'
import { Route as Gta6UltimateEditionRouteImport } from './routes/gta-6-ultimate-edition'
import { Route as Gta6VehiclesRouteImport } from './routes/gta-6-vehicles'
import { Route as Gta6WeaponsRouteImport } from './routes/gta-6-weapons'
import { Route as NewsRouteImport } from './routes/news'
import { Route as SystemRequirementsRouteImport } from './routes/system-requirements'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as WikiRouteImport } from './routes/wiki'
import { Route as AnalysisIndexRouteImport } from './routes/analysis.index'
import { Route as AnalysisSlugRouteImport } from './routes/analysis.$slug'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as ToolsCountdownRouteImport } from './routes/tools.countdown'
import { Route as ToolsHypeCalculatorRouteImport } from './routes/tools.hype-calculator'
import { Route as ToolsMapRouteImport } from './routes/tools.map'
import { Route as ToolsVehicleComparatorRouteImport } from './routes/tools.vehicle-comparator'
import { Route as WikiIndexRouteImport } from './routes/wiki.index'
import { Route as NewsCategoryCategoryRouteImport } from './routes/news.category.$category'
import { Route as WikiTypeSlugRouteImport } from './routes/wiki.$type.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const Gta6ActivitiesRoute = Gta6ActivitiesRouteImport.update({
  id: '/gta-6-activities',
  path: '/gta-6-activities',
  getParentRoute: () => rootRouteImport,
} as any)
const Gta6CharactersRoute = Gta6CharactersRouteImport.update({
  id: '/gta-6-characters',
  path: '/gta-6-characters',
  getParentRoute: () => rootRouteImport,
} as any)
const Gta6GameplayRoute = Gta6GameplayRouteImport.update({
  id: '/gta-6-gameplay',
  path: '/gta-6-gameplay',
  getParentRoute: () => rootRouteImport,
} as any)
const Gta6LeonidaRoute = Gta6LeonidaRouteImport.update({
  id: '/gta-6-leonida',
  path: '/gta-6-leonida',
  getParentRoute: () => rootRouteImport,
} as any)
const Gta6LocationsRoute = Gta6LocationsRouteImport.update({
  id: '/gta-6-locations',
  path: '/gta-6-locations',
  getParentRoute: () => rootRouteImport,
} as any)
const Gta6MapRoute = Gta6MapRouteImport.update({
  id: '/gta-6-map',
  path: '/gta-6-map',
  getParentRoute: () => rootRouteImport,
} as any)
const Gta6NewsRoute = Gta6NewsRouteImport.update({
  id: '/gta-6-news',
  path: '/gta-6-news',
  getParentRoute: () => rootRouteImport,
} as any)
const Gta6OnlineRoute = Gta6OnlineRouteImport.update({
  id: '/gta-6-online',
  path: '/gta-6-online',
  getParentRoute: () => rootRouteImport,
} as any)
const Gta6PcReleaseDateRoute = Gta6PcReleaseDateRouteImport.update({
  id: '/gta-6-pc-release-date',
  path: '/gta-6-pc-release-date',
  getParentRoute: () => rootRouteImport,
} as any)
const Gta6PlatformsRoute = Gta6PlatformsRouteImport.update({
  id: '/gta-6-platforms',
  path: '/gta-6-platforms',
  getParentRoute: () => rootRouteImport,
} as any)
const Gta6PriceRoute = Gta6PriceRouteImport.update({
  id: '/gta-6-price',
  path: '/gta-6-price',
  getParentRoute: () => rootRouteImport,
} as any)
const Gta6ReleaseDateRoute = Gta6ReleaseDateRouteImport.update({
  id: '/gta-6-release-date',
  path: '/gta-6-release-date',
  getParentRoute: () => rootRouteImport,
} as any)
const Gta6TrailersRoute = Gta6TrailersRouteImport.update({
  id: '/gta-6-trailers',
  path: '/gta-6-trailers',
  getParentRoute: () => rootRouteImport,
} as any)
const Gta6UltimateEditionRoute = Gta6UltimateEditionRouteImport.update({
  id: '/gta-6-ultimate-edition',
  path: '/gta-6-ultimate-edition',
  getParentRoute: () => rootRouteImport,
} as any)
const Gta6VehiclesRoute = Gta6VehiclesRouteImport.update({
  id: '/gta-6-vehicles',
  path: '/gta-6-vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const Gta6WeaponsRoute = Gta6WeaponsRouteImport.update({
  id: '/gta-6-weapons',
  path: '/gta-6-weapons',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRequirementsRoute = SystemRequirementsRouteImport.update({
  id: '/system-requirements',
  path: '/system-requirements',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiRoute = WikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisIndexRoute = AnalysisIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnalysisRoute,
} as any)
const AnalysisSlugRoute = AnalysisSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AnalysisRoute,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewsRoute,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsCountdownRoute = ToolsCountdownRouteImport.update({
  id: '/countdown',
  path: '/countdown',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsHypeCalculatorRoute = ToolsHypeCalculatorRouteImport.update({
  id: '/hype-calculator',
  path: '/hype-calculator',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsMapRoute = ToolsMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsVehicleComparatorRoute = ToolsVehicleComparatorRouteImport.update({
  id: '/vehicle-comparator',
  path: '/vehicle-comparator',
  getParentRoute: () => ToolsRoute,
} as any)
const WikiIndexRoute = WikiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WikiRoute,
} as any)
const NewsCategoryCategoryRoute = NewsCategoryCategoryRouteImport.update({
  id: '/category/$category',
  path: '/category/$category',
  getParentRoute: () => NewsRoute,
} as any)
const WikiTypeSlugRoute = WikiTypeSlugRouteImport.update({
  id: '/$type/$slug',
  path: '/$type/$slug',
  getParentRoute: () => WikiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analysis': typeof AnalysisRouteWithChildren
  '/gta-6-activities': typeof Gta6ActivitiesRoute
  '/gta-6-characters': typeof Gta6CharactersRoute
  '/gta-6-gameplay': typeof Gta6GameplayRoute
  '/gta-6-leonida': typeof Gta6LeonidaRoute
  '/gta-6-locations': typeof Gta6LocationsRoute
  '/gta-6-map': typeof Gta6MapRoute
  '/gta-6-news': typeof Gta6NewsRoute
  '/gta-6-online': typeof Gta6OnlineRoute
  '/gta-6-pc-release-date': typeof Gta6PcReleaseDateRoute
  '/gta-6-platforms': typeof Gta6PlatformsRoute
  '/gta-6-price': typeof Gta6PriceRoute
  '/gta-6-release-date': typeof Gta6ReleaseDateRoute
  '/gta-6-trailers': typeof Gta6TrailersRoute
  '/gta-6-ultimate-edition': typeof Gta6UltimateEditionRoute
  '/gta-6-vehicles': typeof Gta6VehiclesRoute
  '/gta-6-weapons': typeof Gta6WeaponsRoute
  '/news': typeof NewsRouteWithChildren
  '/system-requirements': typeof SystemRequirementsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/wiki': typeof WikiRouteWithChildren
  '/analysis/$slug': typeof AnalysisSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/tools/countdown': typeof ToolsCountdownRoute
  '/tools/hype-calculator': typeof ToolsHypeCalculatorRoute
  '/tools/map': typeof ToolsMapRoute
  '/tools/vehicle-comparator': typeof ToolsVehicleComparatorRoute
  '/analysis/': typeof AnalysisIndexRoute
  '/news/': typeof NewsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/wiki/': typeof WikiIndexRoute
  '/news/category/$category': typeof NewsCategoryCategoryRoute
  '/wiki/$type/$slug': typeof WikiTypeSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gta-6-activities': typeof Gta6ActivitiesRoute
  '/gta-6-characters': typeof Gta6CharactersRoute
  '/gta-6-gameplay': typeof Gta6GameplayRoute
  '/gta-6-leonida': typeof Gta6LeonidaRoute
  '/gta-6-locations': typeof Gta6LocationsRoute
  '/gta-6-map': typeof Gta6MapRoute
  '/gta-6-news': typeof Gta6NewsRoute
  '/gta-6-online': typeof Gta6OnlineRoute
  '/gta-6-pc-release-date': typeof Gta6PcReleaseDateRoute
  '/gta-6-platforms': typeof Gta6PlatformsRoute
  '/gta-6-price': typeof Gta6PriceRoute
  '/gta-6-release-date': typeof Gta6ReleaseDateRoute
  '/gta-6-trailers': typeof Gta6TrailersRoute
  '/gta-6-ultimate-edition': typeof Gta6UltimateEditionRoute
  '/gta-6-vehicles': typeof Gta6VehiclesRoute
  '/gta-6-weapons': typeof Gta6WeaponsRoute
  '/system-requirements': typeof SystemRequirementsRoute
  '/analysis/$slug': typeof AnalysisSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/tools/countdown': typeof ToolsCountdownRoute
  '/tools/hype-calculator': typeof ToolsHypeCalculatorRoute
  '/tools/map': typeof ToolsMapRoute
  '/tools/vehicle-comparator': typeof ToolsVehicleComparatorRoute
  '/analysis': typeof AnalysisIndexRoute
  '/news': typeof NewsIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/wiki': typeof WikiIndexRoute
  '/news/category/$category': typeof NewsCategoryCategoryRoute
  '/wiki/$type/$slug': typeof WikiTypeSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analysis': typeof AnalysisRouteWithChildren
  '/gta-6-activities': typeof Gta6ActivitiesRoute
  '/gta-6-characters': typeof Gta6CharactersRoute
  '/gta-6-gameplay': typeof Gta6GameplayRoute
  '/gta-6-leonida': typeof Gta6LeonidaRoute
  '/gta-6-locations': typeof Gta6LocationsRoute
  '/gta-6-map': typeof Gta6MapRoute
  '/gta-6-news': typeof Gta6NewsRoute
  '/gta-6-online': typeof Gta6OnlineRoute
  '/gta-6-pc-release-date': typeof Gta6PcReleaseDateRoute
  '/gta-6-platforms': typeof Gta6PlatformsRoute
  '/gta-6-price': typeof Gta6PriceRoute
  '/gta-6-release-date': typeof Gta6ReleaseDateRoute
  '/gta-6-trailers': typeof Gta6TrailersRoute
  '/gta-6-ultimate-edition': typeof Gta6UltimateEditionRoute
  '/gta-6-vehicles': typeof Gta6VehiclesRoute
  '/gta-6-weapons': typeof Gta6WeaponsRoute
  '/news': typeof NewsRouteWithChildren
  '/system-requirements': typeof SystemRequirementsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/wiki': typeof WikiRouteWithChildren
  '/analysis/$slug': typeof AnalysisSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/tools/countdown': typeof ToolsCountdownRoute
  '/tools/hype-calculator': typeof ToolsHypeCalculatorRoute
  '/tools/map': typeof ToolsMapRoute
  '/tools/vehicle-comparator': typeof ToolsVehicleComparatorRoute
  '/analysis/': typeof AnalysisIndexRoute
  '/news/': typeof NewsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/wiki/': typeof WikiIndexRoute
  '/news/category/$category': typeof NewsCategoryCategoryRoute
  '/wiki/$type/$slug': typeof WikiTypeSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/analysis'
    | '/gta-6-activities'
    | '/gta-6-characters'
    | '/gta-6-gameplay'
    | '/gta-6-leonida'
    | '/gta-6-locations'
    | '/gta-6-map'
    | '/gta-6-news'
    | '/gta-6-online'
    | '/gta-6-pc-release-date'
    | '/gta-6-platforms'
    | '/gta-6-price'
    | '/gta-6-release-date'
    | '/gta-6-trailers'
    | '/gta-6-ultimate-edition'
    | '/gta-6-vehicles'
    | '/gta-6-weapons'
    | '/news'
    | '/system-requirements'
    | '/tools'
    | '/wiki'
    | '/analysis/$slug'
    | '/news/$slug'
    | '/tools/countdown'
    | '/tools/hype-calculator'
    | '/tools/map'
    | '/tools/vehicle-comparator'
    | '/analysis/'
    | '/news/'
    | '/tools/'
    | '/wiki/'
    | '/news/category/$category'
    | '/wiki/$type/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/gta-6-activities'
    | '/gta-6-characters'
    | '/gta-6-gameplay'
    | '/gta-6-leonida'
    | '/gta-6-locations'
    | '/gta-6-map'
    | '/gta-6-news'
    | '/gta-6-online'
    | '/gta-6-pc-release-date'
    | '/gta-6-platforms'
    | '/gta-6-price'
    | '/gta-6-release-date'
    | '/gta-6-trailers'
    | '/gta-6-ultimate-edition'
    | '/gta-6-vehicles'
    | '/gta-6-weapons'
    | '/system-requirements'
    | '/analysis/$slug'
    | '/news/$slug'
    | '/tools/countdown'
    | '/tools/hype-calculator'
    | '/tools/map'
    | '/tools/vehicle-comparator'
    | '/analysis'
    | '/news'
    | '/tools'
    | '/wiki'
    | '/news/category/$category'
    | '/wiki/$type/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/analysis'
    | '/gta-6-activities'
    | '/gta-6-characters'
    | '/gta-6-gameplay'
    | '/gta-6-leonida'
    | '/gta-6-locations'
    | '/gta-6-map'
    | '/gta-6-news'
    | '/gta-6-online'
    | '/gta-6-pc-release-date'
    | '/gta-6-platforms'
    | '/gta-6-price'
    | '/gta-6-release-date'
    | '/gta-6-trailers'
    | '/gta-6-ultimate-edition'
    | '/gta-6-vehicles'
    | '/gta-6-weapons'
    | '/news'
    | '/system-requirements'
    | '/tools'
    | '/wiki'
    | '/analysis/$slug'
    | '/news/$slug'
    | '/tools/countdown'
    | '/tools/hype-calculator'
    | '/tools/map'
    | '/tools/vehicle-comparator'
    | '/analysis/'
    | '/news/'
    | '/tools/'
    | '/wiki/'
    | '/news/category/$category'
    | '/wiki/$type/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnalysisRoute: typeof AnalysisRouteWithChildren
  Gta6ActivitiesRoute: typeof Gta6ActivitiesRoute
  Gta6CharactersRoute: typeof Gta6CharactersRoute
  Gta6GameplayRoute: typeof Gta6GameplayRoute
  Gta6LeonidaRoute: typeof Gta6LeonidaRoute
  Gta6LocationsRoute: typeof Gta6LocationsRoute
  Gta6MapRoute: typeof Gta6MapRoute
  Gta6NewsRoute: typeof Gta6NewsRoute
  Gta6OnlineRoute: typeof Gta6OnlineRoute
  Gta6PcReleaseDateRoute: typeof Gta6PcReleaseDateRoute
  Gta6PlatformsRoute: typeof Gta6PlatformsRoute
  Gta6PriceRoute: typeof Gta6PriceRoute
  Gta6ReleaseDateRoute: typeof Gta6ReleaseDateRoute
  Gta6TrailersRoute: typeof Gta6TrailersRoute
  Gta6UltimateEditionRoute: typeof Gta6UltimateEditionRoute
  Gta6VehiclesRoute: typeof Gta6VehiclesRoute
  Gta6WeaponsRoute: typeof Gta6WeaponsRoute
  NewsRoute: typeof NewsRouteWithChildren
  SystemRequirementsRoute: typeof SystemRequirementsRoute
  ToolsRoute: typeof ToolsRouteWithChildren
  WikiRoute: typeof WikiRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gta-6-activities': {
      id: '/gta-6-activities'
      path: '/gta-6-activities'
      fullPath: '/gta-6-activities'
      preLoaderRoute: typeof Gta6ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gta-6-characters': {
      id: '/gta-6-characters'
      path: '/gta-6-characters'
      fullPath: '/gta-6-characters'
      preLoaderRoute: typeof Gta6CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gta-6-gameplay': {
      id: '/gta-6-gameplay'
      path: '/gta-6-gameplay'
      fullPath: '/gta-6-gameplay'
      preLoaderRoute: typeof Gta6GameplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gta-6-leonida': {
      id: '/gta-6-leonida'
      path: '/gta-6-leonida'
      fullPath: '/gta-6-leonida'
      preLoaderRoute: typeof Gta6LeonidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gta-6-locations': {
      id: '/gta-6-locations'
      path: '/gta-6-locations'
      fullPath: '/gta-6-locations'
      preLoaderRoute: typeof Gta6LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gta-6-map': {
      id: '/gta-6-map'
      path: '/gta-6-map'
      fullPath: '/gta-6-map'
      preLoaderRoute: typeof Gta6MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gta-6-news': {
      id: '/gta-6-news'
      path: '/gta-6-news'
      fullPath: '/gta-6-news'
      preLoaderRoute: typeof Gta6NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gta-6-online': {
      id: '/gta-6-online'
      path: '/gta-6-online'
      fullPath: '/gta-6-online'
      preLoaderRoute: typeof Gta6OnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gta-6-pc-release-date': {
      id: '/gta-6-pc-release-date'
      path: '/gta-6-pc-release-date'
      fullPath: '/gta-6-pc-release-date'
      preLoaderRoute: typeof Gta6PcReleaseDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gta-6-platforms': {
      id: '/gta-6-platforms'
      path: '/gta-6-platforms'
      fullPath: '/gta-6-platforms'
      preLoaderRoute: typeof Gta6PlatformsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gta-6-price': {
      id: '/gta-6-price'
      path: '/gta-6-price'
      fullPath: '/gta-6-price'
      preLoaderRoute: typeof Gta6PriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gta-6-release-date': {
      id: '/gta-6-release-date'
      path: '/gta-6-release-date'
      fullPath: '/gta-6-release-date'
      preLoaderRoute: typeof Gta6ReleaseDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gta-6-trailers': {
      id: '/gta-6-trailers'
      path: '/gta-6-trailers'
      fullPath: '/gta-6-trailers'
      preLoaderRoute: typeof Gta6TrailersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gta-6-ultimate-edition': {
      id: '/gta-6-ultimate-edition'
      path: '/gta-6-ultimate-edition'
      fullPath: '/gta-6-ultimate-edition'
      preLoaderRoute: typeof Gta6UltimateEditionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gta-6-vehicles': {
      id: '/gta-6-vehicles'
      path: '/gta-6-vehicles'
      fullPath: '/gta-6-vehicles'
      preLoaderRoute: typeof Gta6VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gta-6-weapons': {
      id: '/gta-6-weapons'
      path: '/gta-6-weapons'
      fullPath: '/gta-6-weapons'
      preLoaderRoute: typeof Gta6WeaponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-requirements': {
      id: '/system-requirements'
      path: '/system-requirements'
      fullPath: '/system-requirements'
      preLoaderRoute: typeof SystemRequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki': {
      id: '/wiki'
      path: '/wiki'
      fullPath: '/wiki'
      preLoaderRoute: typeof WikiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/': {
      id: '/analysis/'
      path: '/'
      fullPath: '/analysis/'
      preLoaderRoute: typeof AnalysisIndexRouteImport
      parentRoute: typeof AnalysisRoute
    }
    '/analysis/$slug': {
      id: '/analysis/$slug'
      path: '/$slug'
      fullPath: '/analysis/$slug'
      preLoaderRoute: typeof AnalysisSlugRouteImport
      parentRoute: typeof AnalysisRoute
    }
    '/news/': {
      id: '/news/'
      path: '/'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof NewsRoute
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
    '/tools/': {
      id: '/tools/'
      path: '/'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/countdown': {
      id: '/tools/countdown'
      path: '/countdown'
      fullPath: '/tools/countdown'
      preLoaderRoute: typeof ToolsCountdownRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/hype-calculator': {
      id: '/tools/hype-calculator'
      path: '/hype-calculator'
      fullPath: '/tools/hype-calculator'
      preLoaderRoute: typeof ToolsHypeCalculatorRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/map': {
      id: '/tools/map'
      path: '/map'
      fullPath: '/tools/map'
      preLoaderRoute: typeof ToolsMapRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/vehicle-comparator': {
      id: '/tools/vehicle-comparator'
      path: '/vehicle-comparator'
      fullPath: '/tools/vehicle-comparator'
      preLoaderRoute: typeof ToolsVehicleComparatorRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/wiki/': {
      id: '/wiki/'
      path: '/'
      fullPath: '/wiki/'
      preLoaderRoute: typeof WikiIndexRouteImport
      parentRoute: typeof WikiRoute
    }
    '/news/category/$category': {
      id: '/news/category/$category'
      path: '/category/$category'
      fullPath: '/news/category/$category'
      preLoaderRoute: typeof NewsCategoryCategoryRouteImport
      parentRoute: typeof NewsRoute
    }
    '/wiki/$type/$slug': {
      id: '/wiki/$type/$slug'
      path: '/$type/$slug'
      fullPath: '/wiki/$type/$slug'
      preLoaderRoute: typeof WikiTypeSlugRouteImport
      parentRoute: typeof WikiRoute
    }
  }
}

interface AnalysisRouteChildren {
  AnalysisSlugRoute: typeof AnalysisSlugRoute
  AnalysisIndexRoute: typeof AnalysisIndexRoute
}

const AnalysisRouteChildren: AnalysisRouteChildren = {
  AnalysisSlugRoute: AnalysisSlugRoute,
  AnalysisIndexRoute: AnalysisIndexRoute,
}

const AnalysisRouteWithChildren = AnalysisRoute._addFileChildren(
  AnalysisRouteChildren,
)

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
  NewsIndexRoute: typeof NewsIndexRoute
  NewsCategoryCategoryRoute: typeof NewsCategoryCategoryRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
  NewsIndexRoute: NewsIndexRoute,
  NewsCategoryCategoryRoute: NewsCategoryCategoryRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

interface ToolsRouteChildren {
  ToolsCountdownRoute: typeof ToolsCountdownRoute
  ToolsHypeCalculatorRoute: typeof ToolsHypeCalculatorRoute
  ToolsMapRoute: typeof ToolsMapRoute
  ToolsVehicleComparatorRoute: typeof ToolsVehicleComparatorRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsCountdownRoute: ToolsCountdownRoute,
  ToolsHypeCalculatorRoute: ToolsHypeCalculatorRoute,
  ToolsMapRoute: ToolsMapRoute,
  ToolsVehicleComparatorRoute: ToolsVehicleComparatorRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

interface WikiRouteChildren {
  WikiIndexRoute: typeof WikiIndexRoute
  WikiTypeSlugRoute: typeof WikiTypeSlugRoute
}

const WikiRouteChildren: WikiRouteChildren = {
  WikiIndexRoute: WikiIndexRoute,
  WikiTypeSlugRoute: WikiTypeSlugRoute,
}

const WikiRouteWithChildren = WikiRoute._addFileChildren(WikiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnalysisRoute: AnalysisRouteWithChildren,
  Gta6ActivitiesRoute: Gta6ActivitiesRoute,
  Gta6CharactersRoute: Gta6CharactersRoute,
  Gta6GameplayRoute: Gta6GameplayRoute,
  Gta6LeonidaRoute: Gta6LeonidaRoute,
  Gta6LocationsRoute: Gta6LocationsRoute,
  Gta6MapRoute: Gta6MapRoute,
  Gta6NewsRoute: Gta6NewsRoute,
  Gta6OnlineRoute: Gta6OnlineRoute,
  Gta6PcReleaseDateRoute: Gta6PcReleaseDateRoute,
  Gta6PlatformsRoute: Gta6PlatformsRoute,
  Gta6PriceRoute: Gta6PriceRoute,
  Gta6ReleaseDateRoute: Gta6ReleaseDateRoute,
  Gta6TrailersRoute: Gta6TrailersRoute,
  Gta6UltimateEditionRoute: Gta6UltimateEditionRoute,
  Gta6VehiclesRoute: Gta6VehiclesRoute,
  Gta6WeaponsRoute: Gta6WeaponsRoute,
  NewsRoute: NewsRouteWithChildren,
  SystemRequirementsRoute: SystemRequirementsRoute,
  ToolsRoute: ToolsRouteWithChildren,
  WikiRoute: WikiRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
