/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as Gta6CharactersRouteImport } from './routes/gta-6-characters'
import { Route as Gta6MapRouteImport } from './routes/gta-6-map'
import { Route as Gta6NewsRouteImport } from './routes/gta-6-news'
import { Route as Gta6ReleaseDateRouteImport } from './routes/gta-6-release-date'
import { Route as Gta6VehiclesRouteImport } from './routes/gta-6-vehicles'
import { Route as Gta6WeaponsRouteImport } from './routes/gta-6-weapons'
import { Route as NewsRouteImport } from './routes/news'
import { Route as SystemRequirementsRouteImport } from './routes/system-requirements'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as WikiRouteImport } from './routes/wiki'
import { Route as AnalysisIndexRouteImport } from './routes/analysis.index'
import { Route as AnalysisSlugRouteImport } from './routes/analysis.$slug'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as ToolsCountdownRouteImport } from './routes/tools.countdown'
import { Route as ToolsHypeCalculatorRouteImport } from './routes/tools.hype-calculator'
import { Route as ToolsMapRouteImport } from './routes/tools.map'
import { Route as ToolsVehicleComparatorRouteImport } from './routes/tools.vehicle-comparator'
import { Route as WikiIndexRouteImport } from './routes/wiki.index'
import { Route as NewsCategoryCategoryRouteImport } from './routes/news.category.$category'
import { Route as WikiTypeSlugRouteImport } from './routes/wiki.$type.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const Gta6CharactersRoute = Gta6CharactersRouteImport.update({
  id: '/gta-6-characters',
  path: '/gta-6-characters',
  getParentRoute: () => rootRouteImport,
} as any)
const Gta6MapRoute = Gta6MapRouteImport.update({
  id: '/gta-6-map',
  path: '/gta-6-map',
  getParentRoute: () => rootRouteImport,
} as any)
const Gta6NewsRoute = Gta6NewsRouteImport.update({
  id: '/gta-6-news',
  path: '/gta-6-news',
  getParentRoute: () => rootRouteImport,
} as any)
const Gta6ReleaseDateRoute = Gta6ReleaseDateRouteImport.update({
  id: '/gta-6-release-date',
  path: '/gta-6-release-date',
  getParentRoute: () => rootRouteImport,
} as any)
const Gta6VehiclesRoute = Gta6VehiclesRouteImport.update({
  id: '/gta-6-vehicles',
  path: '/gta-6-vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const Gta6WeaponsRoute = Gta6WeaponsRouteImport.update({
  id: '/gta-6-weapons',
  path: '/gta-6-weapons',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRequirementsRoute = SystemRequirementsRouteImport.update({
  id: '/system-requirements',
  path: '/system-requirements',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiRoute = WikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisIndexRoute = AnalysisIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnalysisRoute,
} as any)
const AnalysisSlugRoute = AnalysisSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AnalysisRoute,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewsRoute,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsCountdownRoute = ToolsCountdownRouteImport.update({
  id: '/countdown',
  path: '/countdown',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsHypeCalculatorRoute = ToolsHypeCalculatorRouteImport.update({
  id: '/hype-calculator',
  path: '/hype-calculator',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsMapRoute = ToolsMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsVehicleComparatorRoute = ToolsVehicleComparatorRouteImport.update({
  id: '/vehicle-comparator',
  path: '/vehicle-comparator',
  getParentRoute: () => ToolsRoute,
} as any)
const WikiIndexRoute = WikiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WikiRoute,
} as any)
const NewsCategoryCategoryRoute = NewsCategoryCategoryRouteImport.update({
  id: '/category/$category',
  path: '/category/$category',
  getParentRoute: () => NewsRoute,
} as any)
const WikiTypeSlugRoute = WikiTypeSlugRouteImport.update({
  id: '/$type/$slug',
  path: '/$type/$slug',
  getParentRoute: () => WikiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRouteWithChildren
  '/gta-6-characters': typeof Gta6CharactersRoute
  '/gta-6-map': typeof Gta6MapRoute
  '/gta-6-news': typeof Gta6NewsRoute
  '/gta-6-release-date': typeof Gta6ReleaseDateRoute
  '/gta-6-vehicles': typeof Gta6VehiclesRoute
  '/gta-6-weapons': typeof Gta6WeaponsRoute
  '/news': typeof NewsRouteWithChildren
  '/system-requirements': typeof SystemRequirementsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/wiki': typeof WikiRouteWithChildren
  '/analysis/$slug': typeof AnalysisSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/tools/countdown': typeof ToolsCountdownRoute
  '/tools/hype-calculator': typeof ToolsHypeCalculatorRoute
  '/tools/map': typeof ToolsMapRoute
  '/tools/vehicle-comparator': typeof ToolsVehicleComparatorRoute
  '/analysis/': typeof AnalysisIndexRoute
  '/news/': typeof NewsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/wiki/': typeof WikiIndexRoute
  '/news/category/$category': typeof NewsCategoryCategoryRoute
  '/wiki/$type/$slug': typeof WikiTypeSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gta-6-characters': typeof Gta6CharactersRoute
  '/gta-6-map': typeof Gta6MapRoute
  '/gta-6-news': typeof Gta6NewsRoute
  '/gta-6-release-date': typeof Gta6ReleaseDateRoute
  '/gta-6-vehicles': typeof Gta6VehiclesRoute
  '/gta-6-weapons': typeof Gta6WeaponsRoute
  '/system-requirements': typeof SystemRequirementsRoute
  '/analysis/$slug': typeof AnalysisSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/tools/countdown': typeof ToolsCountdownRoute
  '/tools/hype-calculator': typeof ToolsHypeCalculatorRoute
  '/tools/map': typeof ToolsMapRoute
  '/tools/vehicle-comparator': typeof ToolsVehicleComparatorRoute
  '/analysis': typeof AnalysisIndexRoute
  '/news': typeof NewsIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/wiki': typeof WikiIndexRoute
  '/news/category/$category': typeof NewsCategoryCategoryRoute
  '/wiki/$type/$slug': typeof WikiTypeSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRouteWithChildren
  '/gta-6-characters': typeof Gta6CharactersRoute
  '/gta-6-map': typeof Gta6MapRoute
  '/gta-6-news': typeof Gta6NewsRoute
  '/gta-6-release-date': typeof Gta6ReleaseDateRoute
  '/gta-6-vehicles': typeof Gta6VehiclesRoute
  '/gta-6-weapons': typeof Gta6WeaponsRoute
  '/news': typeof NewsRouteWithChildren
  '/system-requirements': typeof SystemRequirementsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/wiki': typeof WikiRouteWithChildren
  '/analysis/$slug': typeof AnalysisSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/tools/countdown': typeof ToolsCountdownRoute
  '/tools/hype-calculator': typeof ToolsHypeCalculatorRoute
  '/tools/map': typeof ToolsMapRoute
  '/tools/vehicle-comparator': typeof ToolsVehicleComparatorRoute
  '/analysis/': typeof AnalysisIndexRoute
  '/news/': typeof NewsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/wiki/': typeof WikiIndexRoute
  '/news/category/$category': typeof NewsCategoryCategoryRoute
  '/wiki/$type/$slug': typeof WikiTypeSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/gta-6-characters'
    | '/gta-6-map'
    | '/gta-6-news'
    | '/gta-6-release-date'
    | '/gta-6-vehicles'
    | '/gta-6-weapons'
    | '/news'
    | '/system-requirements'
    | '/tools'
    | '/wiki'
    | '/analysis/$slug'
    | '/news/$slug'
    | '/tools/countdown'
    | '/tools/hype-calculator'
    | '/tools/map'
    | '/tools/vehicle-comparator'
    | '/analysis/'
    | '/news/'
    | '/tools/'
    | '/wiki/'
    | '/news/category/$category'
    | '/wiki/$type/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gta-6-characters'
    | '/gta-6-map'
    | '/gta-6-news'
    | '/gta-6-release-date'
    | '/gta-6-vehicles'
    | '/gta-6-weapons'
    | '/system-requirements'
    | '/analysis/$slug'
    | '/news/$slug'
    | '/tools/countdown'
    | '/tools/hype-calculator'
    | '/tools/map'
    | '/tools/vehicle-comparator'
    | '/analysis'
    | '/news'
    | '/tools'
    | '/wiki'
    | '/news/category/$category'
    | '/wiki/$type/$slug'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/gta-6-characters'
    | '/gta-6-map'
    | '/gta-6-news'
    | '/gta-6-release-date'
    | '/gta-6-vehicles'
    | '/gta-6-weapons'
    | '/news'
    | '/system-requirements'
    | '/tools'
    | '/wiki'
    | '/analysis/$slug'
    | '/news/$slug'
    | '/tools/countdown'
    | '/tools/hype-calculator'
    | '/tools/map'
    | '/tools/vehicle-comparator'
    | '/analysis/'
    | '/news/'
    | '/tools/'
    | '/wiki/'
    | '/news/category/$category'
    | '/wiki/$type/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRouteWithChildren
  Gta6CharactersRoute: typeof Gta6CharactersRoute
  Gta6MapRoute: typeof Gta6MapRoute
  Gta6NewsRoute: typeof Gta6NewsRoute
  Gta6ReleaseDateRoute: typeof Gta6ReleaseDateRoute
  Gta6VehiclesRoute: typeof Gta6VehiclesRoute
  Gta6WeaponsRoute: typeof Gta6WeaponsRoute
  NewsRoute: typeof NewsRouteWithChildren
  SystemRequirementsRoute: typeof SystemRequirementsRoute
  ToolsRoute: typeof ToolsRouteWithChildren
  WikiRoute: typeof WikiRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gta-6-characters': {
      id: '/gta-6-characters'
      path: '/gta-6-characters'
      fullPath: '/gta-6-characters'
      preLoaderRoute: typeof Gta6CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gta-6-map': {
      id: '/gta-6-map'
      path: '/gta-6-map'
      fullPath: '/gta-6-map'
      preLoaderRoute: typeof Gta6MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gta-6-news': {
      id: '/gta-6-news'
      path: '/gta-6-news'
      fullPath: '/gta-6-news'
      preLoaderRoute: typeof Gta6NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gta-6-release-date': {
      id: '/gta-6-release-date'
      path: '/gta-6-release-date'
      fullPath: '/gta-6-release-date'
      preLoaderRoute: typeof Gta6ReleaseDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gta-6-vehicles': {
      id: '/gta-6-vehicles'
      path: '/gta-6-vehicles'
      fullPath: '/gta-6-vehicles'
      preLoaderRoute: typeof Gta6VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gta-6-weapons': {
      id: '/gta-6-weapons'
      path: '/gta-6-weapons'
      fullPath: '/gta-6-weapons'
      preLoaderRoute: typeof Gta6WeaponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-requirements': {
      id: '/system-requirements'
      path: '/system-requirements'
      fullPath: '/system-requirements'
      preLoaderRoute: typeof SystemRequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki': {
      id: '/wiki'
      path: '/wiki'
      fullPath: '/wiki'
      preLoaderRoute: typeof WikiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/': {
      id: '/analysis/'
      path: '/'
      fullPath: '/analysis/'
      preLoaderRoute: typeof AnalysisIndexRouteImport
      parentRoute: typeof AnalysisRoute
    }
    '/analysis/$slug': {
      id: '/analysis/$slug'
      path: '/$slug'
      fullPath: '/analysis/$slug'
      preLoaderRoute: typeof AnalysisSlugRouteImport
      parentRoute: typeof AnalysisRoute
    }
    '/news/': {
      id: '/news/'
      path: '/'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof NewsRoute
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
    '/tools/': {
      id: '/tools/'
      path: '/'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/countdown': {
      id: '/tools/countdown'
      path: '/countdown'
      fullPath: '/tools/countdown'
      preLoaderRoute: typeof ToolsCountdownRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/hype-calculator': {
      id: '/tools/hype-calculator'
      path: '/hype-calculator'
      fullPath: '/tools/hype-calculator'
      preLoaderRoute: typeof ToolsHypeCalculatorRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/map': {
      id: '/tools/map'
      path: '/map'
      fullPath: '/tools/map'
      preLoaderRoute: typeof ToolsMapRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/vehicle-comparator': {
      id: '/tools/vehicle-comparator'
      path: '/vehicle-comparator'
      fullPath: '/tools/vehicle-comparator'
      preLoaderRoute: typeof ToolsVehicleComparatorRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/wiki/': {
      id: '/wiki/'
      path: '/'
      fullPath: '/wiki/'
      preLoaderRoute: typeof WikiIndexRouteImport
      parentRoute: typeof WikiRoute
    }
    '/news/category/$category': {
      id: '/news/category/$category'
      path: '/category/$category'
      fullPath: '/news/category/$category'
      preLoaderRoute: typeof NewsCategoryCategoryRouteImport
      parentRoute: typeof NewsRoute
    }
    '/wiki/$type/$slug': {
      id: '/wiki/$type/$slug'
      path: '/$type/$slug'
      fullPath: '/wiki/$type/$slug'
      preLoaderRoute: typeof WikiTypeSlugRouteImport
      parentRoute: typeof WikiRoute
    }
  }
}

interface AnalysisRouteChildren {
  AnalysisSlugRoute: typeof AnalysisSlugRoute
  AnalysisIndexRoute: typeof AnalysisIndexRoute
}

const AnalysisRouteChildren: AnalysisRouteChildren = {
  AnalysisSlugRoute: AnalysisSlugRoute,
  AnalysisIndexRoute: AnalysisIndexRoute,
}

const AnalysisRouteWithChildren = AnalysisRoute._addFileChildren(
  AnalysisRouteChildren,
)

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
  NewsIndexRoute: typeof NewsIndexRoute
  NewsCategoryCategoryRoute: typeof NewsCategoryCategoryRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
  NewsIndexRoute: NewsIndexRoute,
  NewsCategoryCategoryRoute: NewsCategoryCategoryRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

interface ToolsRouteChildren {
  ToolsCountdownRoute: typeof ToolsCountdownRoute
  ToolsHypeCalculatorRoute: typeof ToolsHypeCalculatorRoute
  ToolsMapRoute: typeof ToolsMapRoute
  ToolsVehicleComparatorRoute: typeof ToolsVehicleComparatorRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsCountdownRoute: ToolsCountdownRoute,
  ToolsHypeCalculatorRoute: ToolsHypeCalculatorRoute,
  ToolsMapRoute: ToolsMapRoute,
  ToolsVehicleComparatorRoute: ToolsVehicleComparatorRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

interface WikiRouteChildren {
  WikiIndexRoute: typeof WikiIndexRoute
  WikiTypeSlugRoute: typeof WikiTypeSlugRoute
}

const WikiRouteChildren: WikiRouteChildren = {
  WikiIndexRoute: WikiIndexRoute,
  WikiTypeSlugRoute: WikiTypeSlugRoute,
}

const WikiRouteWithChildren = WikiRoute._addFileChildren(WikiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRouteWithChildren,
  Gta6CharactersRoute: Gta6CharactersRoute,
  Gta6MapRoute: Gta6MapRoute,
  Gta6NewsRoute: Gta6NewsRoute,
  Gta6ReleaseDateRoute: Gta6ReleaseDateRoute,
  Gta6VehiclesRoute: Gta6VehiclesRoute,
  Gta6WeaponsRoute: Gta6WeaponsRoute,
  NewsRoute: NewsRouteWithChildren,
  SystemRequirementsRoute: SystemRequirementsRoute,
  ToolsRoute: ToolsRouteWithChildren,
  WikiRoute: WikiRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
